In [2]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive

In [0]:
import pandas as pd

In [18]:
data_file = 'drive/My Drive/Expenses/expenseList.csv'
data = pd.read_csv(data_file)
data

    Unnamed: 0  Amount Payer Currency                        Date
0          0.0   30.39     V      EUR  2019-11-30 22:16:54.436077
1          1.0   10.75     V      EUR  2019-11-30 22:16:54.436077
2          2.0    8.00     A      EUR  2019-11-30 22:16:54.436077
3          3.0    8.72     V      EUR  2019-11-30 22:16:54.436077
4          4.0   11.57     A      EUR  2019-11-30 22:16:54.436077
5          5.0    7.11     A      EUR  2019-11-30 22:16:54.436077
6          6.0   27.47     A      EUR  2019-11-30 22:16:54.436077
7          7.0    8.95     V      EUR  2019-11-30 22:16:54.436077
8          8.0   22.05     V      EUR  2019-11-30 22:16:54.436077
9          9.0    7.52     V      EUR  2019-11-30 22:16:54.436077
10        10.0   16.47     A      EUR  2019-11-30 22:16:54.436077
11        11.0   19.13     A      EUR  2019-11-30 22:16:54.436077
12        12.0    6.77     A      EUR  2019-11-30 22:16:54.436077
13        13.0   15.85     V      EUR  2019-11-30 22:16:54.436077
14        14.0    4.00     V      EUR  2019-11-30 22:16:54.436077
15        15.0    8.00     A      EUR  2019-11-30 22:16:54.436077
16        16.0   24.53     A      EUR  2019-11-30 22:16:54.436077
17        17.0    8.16     V      EUR  2019-11-30 22:16:54.436077

In [14]:
while True:
    answer = input("Add new expense:(y/n)")
    if answer == "y":
        amount: float = input("Enter the amount of the expense:")
        currency_index = input("Enter 0 for EUR 1 for MKD:")
        while currency_index != "0" and currency_index != "1":
          currency_index = input("Enter 0 for EUR 1 for MKD:")
        if currency_index == '0':
          currency = 'EUR'
        elif currency_index == '1':
          currency = 'MKD'
        date = pd.Timestamp.now()
        payer = input("Enter who payed:(V/A)")
        while payer != "V" and payer != "A":
            payer = input("Enter who payed:(V/A)")
        data = data.append({'Currency': currency, 'Date': date, 'Amount': amount, 'Payer': payer}, ignore_index=True, sort=False)
        #data.loc[len(data)] = [amount, payer]
        print(data.head())
    else:
        break
        
data.to_csv(data_file, index=False)

Add new expense:(y/n)y
Enter the amount of the expense:1000
Enter 0 for EUR 1 for MKD:0
Enter who payed:(V/A)A
   Unnamed: 0 Amount Payer Currency                        Date
0         0.0  30.39     V      EUR  2019-11-30 22:16:54.436077
1         1.0  10.75     V      EUR  2019-11-30 22:16:54.436077
2         2.0      8     A      EUR  2019-11-30 22:16:54.436077
3         3.0   8.72     V      EUR  2019-11-30 22:16:54.436077
4         4.0  11.57     A      EUR  2019-11-30 22:16:54.436077
Add new expense:(y/n)n